# Generated by Django 3.2.8 on 2021-12-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='main.Certificate'),
        ),
    ]
