# Generated by Django 3.2.8 on 2021-12-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_cloud',
            field=models.BooleanField(default=False),
        ),
    ]
