# Generated by Django 3.2.8 on 2021-12-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_certificate_is_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
