# Generated by Django 3.2.8 on 2021-12-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211230_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
