# Generated by Django 3.2.8 on 2021-12-30 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
